# Generated by Django 3.1.7 on 2021-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=36, unique=True)),
                ('moves', models.CharField(max_length=98)),
                ('winner', models.CharField(max_length=5)),
            ],
        ),
    ]
