# Generated by Django 3.1.7 on 2021-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
